# FAST-LIO pose driven KITTI config (cars only)
DATASET: 'kitti'
SPLIT: 'val'
DETECTOR: gt
DATASET_ROOT: "data/kitti/datasets/"
DETECTIONS_ROOT: "data/base_version_fastlio/kitti/"
SAVE_PATH: 'results/'
TRACKING_MODE: 'ONLINE'
IS_RV_MATCHING: True
FRAME_RATE: 10
TRACKING_SEQS: [0]

CATEGORY_LIST: ['car']
CATEGORY_MAP_TO_NUMBER : {
    "car": 0,
}

MATCHING:
  BEV:
    COST_STATE: {0: "Predict"}
    COST_MODE: {0: "RO_GDIOU_3D"}
    MATCHING_MODE: Hungarian
  RV:
    COST_STATE: {0: "Predict"}
    COST_MODE: {0: "SDIOU_2D"}
    MATCHING_MODE : Greedy

THRESHOLD:
  GLOBAL_TRACK_SCORE: 1.4
  NMS_THRE: {0: 0.08}
  INPUT_SCORE:
    ONLINE: {0: 0.375}
    OFFLINE: {0: 0.3775}
  COST_STATE_PREDICT_RATION: {0: 0.5}
  BEV:
    COST_THRE: {0: 1.4}
    WEIGHT_RO_GDIOU: {0: {"w1": 1.0, "w2": 1.0}}
  RV:
    COST_THRE: {0: -0.3}

  TRAJECTORY_THRE:
    CACHE_BBOX_LENGTH: {0: 1000}
    PREDICT_BBOX_LENGTH: {0: 30}
    MAX_UNMATCH_LENGTH: {0: 0}
    CONFIRMED_TRACK_LENGTH: {0: 1}
    DELET_OUT_VIEW_LENGTH: {0: 0}
    CONFIRMED_DET_SCORE: {0: 0.7}
    IS_FILTER_PREDICT_BOX: {0: 0}
    CONFIRMED_MATCHED_SCORE: {0: 0.3}

KALMAN_FILTER_POSE:
  MOTION_MODE: {0: "CV"}
  CV:
    N: 4
    M: 2
    NOISE:
      0:
        P: [1, 1, 500, 500]
        Q: [0.5, 0.5, 5, 5]
        R: [0.1, 0.1]

KALMAN_FILTER_SIZE:
  MOTION_MODE: {0: "CV"}
  CV:
    N: 4
    M: 2
    NOISE:
      0:
        P: [1.0, 1.0, 10.0, 10.0]
        Q: [0.5, 0.5, 1.5, 1.5]
        R: [0.02, 0.02]

KALMAN_FILTER_YAW:
  MOTION_MODE: {0: "CV"}
  CV:
    N: 2
    M: 2
    NOISE:
      0:
        P: [0.1, 0.1]
        Q: [0.1, 0.1]
        R: [0.2, 5.0]

KALMAN_FILTER_RVBOX:
  MOTION_MODE: {0: "CV"}
  CV:
    N: 8
    M: 4
    NOISE:
      0:
        P: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        Q: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
        R: [0.1, 0.1, 0.1, 0.1]
